project:
  type: website
  output-dir: docs

website:
  title: "Primeros pasos en análisis de datos con R"
  site-url: "https://gastonbecerra.github.io/primeros-pasos-r/"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Módulo 1
        href: modulo-1.qmd
      - text: Módulo 2
        href: modulo-2.qmd
      - text: Módulo 3
        href: modulo-3.qmd
      - text: Módulo 4
        href: modulo-4.qmd
    right:
      - icon: github
        href: https://github.com/gastonbecerra/primeros-pasos-r

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contenidos
    code-copy: true
    code-overflow: wrap
    lang: es

execute:
  freeze: auto
