project:
  type: website
  output-dir: docs

website:
  title: "Primeros pasos en análisis de datos con R"
  site-url: "https://gastonbecerra.github.io/primeros-pasos-r/"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Primero
        href: modulo-1.qmd
      - text: Segundo
        href: modulo-2.qmd
      - text: Tercero
        href: modulo-3.qmd
      - text: Cuarto
        href: modulo-4b.qmd
      - text: Sigamos!
        href: modulo-5.qmd
    right:
      - icon: github
        href: https://github.com/gastonbecerra/primeros-pasos-r

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contenidos
    code-copy: true
    code-overflow: wrap
    lang: es

execute:
  freeze: auto
